/**
 * Test User Constants
 *
 * Hardcoded test users for development environment only.
 * Used by /dev/login page and seeding script.
 *
 * SECURITY: Only accessible when NODE_ENV=development
 */

export interface TestUser {
  id: string;
  email: string;
  instagram_username: string;
  instagram_id: string;
  account_type: 'fan' | 'artist_free' | 'artist_pro';
  artist?: {
    id: string;
    name: string;
    instagram_handle: string;
    city: string;
    state: string;
    slug: string;
  };
}

/**
 * Test User Definitions
 *
 * These UUIDs will be generated by the seeding script on first run.
 * Update these values after running scripts/seed/create-test-users.ts
 */
export const TEST_USERS: Record<string, TestUser> = {
  UNCLAIMED: {
    id: 'test-unclaimed-user-id', // No auth user for unclaimed
    email: 'unclaimed@test.inkdex.io',
    instagram_username: 'test_unclaimed_artist',
    instagram_id: 'test_unclaimed_ig_id',
    account_type: 'fan',
    artist: {
      id: 'd1b27ae8-b2db-4496-8cb1-dc0698599d93',
      name: 'Jamie Chen',
      instagram_handle: 'test_unclaimed_artist',
      city: 'Austin',
      state: 'Texas',
      slug: 'jamie-chen',
    },
  },

  FREE: {
    id: '7cde2a51-2ab5-42a5-b0d3-9541f0e31c21',
    email: 'free@test.inkdex.io',
    instagram_username: 'test_free_artist',
    instagram_id: 'test_free_ig_id',
    account_type: 'artist_free',
    artist: {
      id: '9ee81644-6619-438e-a83f-928accb8c317',
      name: 'Alex Rivera',
      instagram_handle: 'test_free_artist',
      city: 'Los Angeles',
      state: 'California',
      slug: 'alex-rivera',
    },
  },

  PRO: {
    id: '34f20c4e-03b3-4806-a9d4-5e60acd02ddd',
    email: 'pro@test.inkdex.io',
    instagram_username: 'test_pro_artist',
    instagram_id: 'test_pro_ig_id',
    account_type: 'artist_pro',
    artist: {
      id: 'da482c81-5ea6-4451-acc4-c2da7c290366',
      name: 'Morgan Black',
      instagram_handle: 'test_pro_artist',
      city: 'New York',
      state: 'New York',
      slug: 'morgan-black',
    },
  },
};

/**
 * Get all test users as an array
 */
export function getAllTestUsers(): TestUser[] {
  return Object.values(TEST_USERS);
}

/**
 * Get test user by ID
 */
export function getTestUserById(id: string): TestUser | undefined {
  return getAllTestUsers().find((user) => user.id === id);
}

/**
 * Get test user by email
 */
export function getTestUserByEmail(email: string): TestUser | undefined {
  return getAllTestUsers().find((user) => user.email === email);
}

/**
 * Check if a user ID is a test user
 */
export function isTestUser(userId: string): boolean {
  return getAllTestUsers().some((user) => user.id === userId);
}

/**
 * Test user credentials for dropdown display
 */
export const TEST_USER_OPTIONS = [
  {
    value: 'UNCLAIMED',
    label: 'Unclaimed Artist (Jamie Chen)',
    description: 'Test claim flow',
    tier: 'Unclaimed',
  },
  {
    value: 'FREE',
    label: 'Free Tier Artist (Alex Rivera)',
    description: 'Test free dashboard',
    tier: 'Free',
  },
  {
    value: 'PRO',
    label: 'Pro Tier Artist (Morgan Black)',
    description: 'Test pro features',
    tier: 'Pro',
  },
] as const;

/**
 * Source artist IDs to clone portfolio images from
 * These will be real existing artists in the database
 */
export const SOURCE_ARTISTS_FOR_CLONING = {
  UNCLAIMED: null, // Will be selected by seed script (Austin artist with 12+ images)
  FREE: null, // Will be selected by seed script (LA artist with 18+ images)
  PRO: null, // Will be selected by seed script (NYC artist with 20+ images)
};
