/**
 * Supported cities for Inkdex
 * Based on Phase 0 market analysis (Dec 29, 2025)
 */

export const CITIES = [
  {
    name: 'Austin',
    slug: 'austin',
    state: 'TX',
    fullName: 'Austin, TX',
    opportunityScore: 78,
    monthlySearches: 262100,
    competition: 46,
  },
  {
    name: 'Los Angeles',
    slug: 'los-angeles',
    state: 'CA',
    fullName: 'Los Angeles, CA',
    opportunityScore: 77,
    monthlySearches: 261920,
    competition: 52,
  },
  {
    name: 'Atlanta',
    slug: 'atlanta',
    state: 'GA',
    fullName: 'Atlanta, GA',
    opportunityScore: 75,
    monthlySearches: 250000,
    competition: 50,
  },
  {
    name: 'Chicago',
    slug: 'chicago',
    state: 'IL',
    fullName: 'Chicago, IL',
    opportunityScore: 81,
    monthlySearches: 269350,
    competition: 42,
  },
  {
    name: 'New York',
    slug: 'new-york',
    state: 'NY',
    fullName: 'New York, NY',
    opportunityScore: 80,
    monthlySearches: 266530,
    competition: 42,
  },
  {
    name: 'Seattle',
    slug: 'seattle',
    state: 'WA',
    fullName: 'Seattle, WA',
    opportunityScore: 78,
    monthlySearches: 258260,
    competition: 48,
  },
  {
    name: 'Portland',
    slug: 'portland',
    state: 'OR',
    fullName: 'Portland, OR',
    opportunityScore: 77,
    monthlySearches: 258530,
    competition: 54,
  },
  {
    name: 'Miami',
    slug: 'miami',
    state: 'FL',
    fullName: 'Miami, FL',
    opportunityScore: 76,
    monthlySearches: 254910,
    competition: 54,
  },
  // Tier 1 Expansion - Lowest Competition (11-14%)
  {
    name: 'Richmond',
    slug: 'richmond',
    state: 'VA',
    fullName: 'Richmond, VA',
    opportunityScore: 84,
    monthlySearches: 254000,
    competition: 13,
  },
  {
    name: 'Asheville',
    slug: 'asheville',
    state: 'NC',
    fullName: 'Asheville, NC',
    opportunityScore: 84,
    monthlySearches: 250000,
    competition: 11,
  },
  {
    name: 'Charlotte',
    slug: 'charlotte',
    state: 'NC',
    fullName: 'Charlotte, NC',
    opportunityScore: 84,
    monthlySearches: 256000,
    competition: 14,
  },
  // Tier 2 Expansion - Strong Mid-Market (22-42%)
  {
    name: 'Philadelphia',
    slug: 'philadelphia',
    state: 'PA',
    fullName: 'Philadelphia, PA',
    opportunityScore: 82,
    monthlySearches: 255000,
    competition: 27,
  },
  {
    name: 'Columbus',
    slug: 'columbus',
    state: 'OH',
    fullName: 'Columbus, OH',
    opportunityScore: 81,
    monthlySearches: 252000,
    competition: 25,
  },
  {
    name: 'Salt Lake City',
    slug: 'salt-lake-city',
    state: 'UT',
    fullName: 'Salt Lake City, UT',
    opportunityScore: 81,
    monthlySearches: 251000,
    competition: 22,
  },
  {
    name: 'Nashville',
    slug: 'nashville',
    state: 'TN',
    fullName: 'Nashville, TN',
    opportunityScore: 80,
    monthlySearches: 266000,
    competition: 38,
  },
  {
    name: 'San Francisco',
    slug: 'san-francisco',
    state: 'CA',
    fullName: 'San Francisco, CA',
    opportunityScore: 80,
    monthlySearches: 254000,
    competition: 42,
  },
  // Tier 3 Expansion - High Volume Markets (297k-317k searches)
  {
    name: 'Phoenix',
    slug: 'phoenix',
    state: 'AZ',
    fullName: 'Phoenix, AZ',
    opportunityScore: 79,
    monthlySearches: 317000,
    competition: 45,
  },
  {
    name: 'Las Vegas',
    slug: 'las-vegas',
    state: 'NV',
    fullName: 'Las Vegas, NV',
    opportunityScore: 80,
    monthlySearches: 297000,
    competition: 42,
  },
  {
    name: 'San Diego',
    slug: 'san-diego',
    state: 'CA',
    fullName: 'San Diego, CA',
    opportunityScore: 77,
    monthlySearches: 266000,
    competition: 55,
  },
  {
    name: 'San Antonio',
    slug: 'san-antonio',
    state: 'TX',
    fullName: 'San Antonio, TX',
    opportunityScore: 79,
    monthlySearches: 259000,
    competition: 36,
  },
  {
    name: 'Tampa',
    slug: 'tampa',
    state: 'FL',
    fullName: 'Tampa, FL',
    opportunityScore: 78,
    monthlySearches: 258000,
    competition: 41,
  },
  // Batch 2 Expansion - Top Tier (84-85/100)
  {
    name: 'Kansas City',
    slug: 'kansas-city',
    state: 'MO',
    fullName: 'Kansas City, MO',
    opportunityScore: 85,
    monthlySearches: 253820,
    competition: 14,
  },
  {
    name: 'New Orleans',
    slug: 'new-orleans',
    state: 'LA',
    fullName: 'New Orleans, LA',
    opportunityScore: 84,
    monthlySearches: 258080,
    competition: 14,
  },
  {
    name: 'Detroit',
    slug: 'detroit',
    state: 'MI',
    fullName: 'Detroit, MI',
    opportunityScore: 84,
    monthlySearches: 249020,
    competition: 10,
  },
  {
    name: 'Providence',
    slug: 'providence',
    state: 'RI',
    fullName: 'Providence, RI',
    opportunityScore: 84,
    monthlySearches: 248840,
    competition: 9,
  },
  {
    name: 'Charleston',
    slug: 'charleston',
    state: 'SC',
    fullName: 'Charleston, SC',
    opportunityScore: 84,
    monthlySearches: 249480,
    competition: 10,
  },
  {
    name: 'Albuquerque',
    slug: 'albuquerque',
    state: 'NM',
    fullName: 'Albuquerque, NM',
    opportunityScore: 84,
    monthlySearches: 254020,
    competition: 11,
  },
  {
    name: 'El Paso',
    slug: 'el-paso',
    state: 'TX',
    fullName: 'El Paso, TX',
    opportunityScore: 84,
    monthlySearches: 250890,
    competition: 14,
  },
  {
    name: 'Baltimore',
    slug: 'baltimore',
    state: 'MD',
    fullName: 'Baltimore, MD',
    opportunityScore: 84,
    monthlySearches: 251190,
    competition: 13,
  },
  {
    name: 'Buffalo',
    slug: 'buffalo',
    state: 'NY',
    fullName: 'Buffalo, NY',
    opportunityScore: 84,
    monthlySearches: 250480,
    competition: 10,
  },
  // Batch 2 Expansion - Strong Second Tier (83/100)
  {
    name: 'Minneapolis',
    slug: 'minneapolis',
    state: 'MN',
    fullName: 'Minneapolis, MN',
    opportunityScore: 83,
    monthlySearches: 254340,
    competition: 17,
  },
  {
    name: 'Tucson',
    slug: 'tucson',
    state: 'AZ',
    fullName: 'Tucson, AZ',
    opportunityScore: 83,
    monthlySearches: 254440,
    competition: 16,
  },
  {
    name: 'Savannah',
    slug: 'savannah',
    state: 'GA',
    fullName: 'Savannah, GA',
    opportunityScore: 83,
    monthlySearches: 255680,
    competition: 13,
  },
  {
    name: 'Madison',
    slug: 'madison',
    state: 'WI',
    fullName: 'Madison, WI',
    opportunityScore: 83,
    monthlySearches: 251880,
    competition: 11,
  },
  {
    name: 'Ann Arbor',
    slug: 'ann-arbor',
    state: 'MI',
    fullName: 'Ann Arbor, MI',
    opportunityScore: 83,
    monthlySearches: 248700,
    competition: 11,
  },
  {
    name: 'Chapel Hill',
    slug: 'chapel-hill',
    state: 'NC',
    fullName: 'Chapel Hill, NC',
    opportunityScore: 83,
    monthlySearches: 246390,
    competition: 10,
  },
  // Batch 2 Expansion - Solid Third Tier (80-82/100)
  {
    name: 'Durham',
    slug: 'durham',
    state: 'NC',
    fullName: 'Durham, NC',
    opportunityScore: 82,
    monthlySearches: 249280,
    competition: 16,
  },
  {
    name: 'Oklahoma City',
    slug: 'oklahoma-city',
    state: 'OK',
    fullName: 'Oklahoma City, OK',
    opportunityScore: 82,
    monthlySearches: 253220,
    competition: 17,
  },
  {
    name: 'Raleigh',
    slug: 'raleigh',
    state: 'NC',
    fullName: 'Raleigh, NC',
    opportunityScore: 81,
    monthlySearches: 255700,
    competition: 22,
  },
  {
    name: 'Honolulu',
    slug: 'honolulu',
    state: 'HI',
    fullName: 'Honolulu, HI',
    opportunityScore: 81,
    monthlySearches: 250500,
    competition: 22,
  },
  {
    name: 'Fort Lauderdale',
    slug: 'fort-lauderdale',
    state: 'FL',
    fullName: 'Fort Lauderdale, FL',
    opportunityScore: 81,
    monthlySearches: 250340,
    competition: 25,
  },
  {
    name: 'Boise',
    slug: 'boise',
    state: 'ID',
    fullName: 'Boise, ID',
    opportunityScore: 81,
    monthlySearches: 252690,
    competition: 26,
  },
  {
    name: 'Pittsburgh',
    slug: 'pittsburgh',
    state: 'PA',
    fullName: 'Pittsburgh, PA',
    opportunityScore: 80,
    monthlySearches: 252160,
    competition: 28,
  },
  {
    name: 'Boulder',
    slug: 'boulder',
    state: 'CO',
    fullName: 'Boulder, CO',
    opportunityScore: 80,
    monthlySearches: 247640,
    competition: 26,
  },
  {
    name: 'Indianapolis',
    slug: 'indianapolis',
    state: 'IN',
    fullName: 'Indianapolis, IN',
    opportunityScore: 80,
    monthlySearches: 251670,
    competition: 29,
  },
  {
    name: 'Sacramento',
    slug: 'sacramento',
    state: 'CA',
    fullName: 'Sacramento, CA',
    opportunityScore: 79,
    monthlySearches: 251120,
    competition: 30,
  },
  // Batch 3 Expansion - Top Tier (84/100) - Jan 2026
  {
    name: 'St. Louis',
    slug: 'st-louis',
    state: 'MO',
    fullName: 'St. Louis, MO',
    opportunityScore: 84,
    monthlySearches: 255080,
    competition: 16,
  },
  {
    name: 'Cleveland',
    slug: 'cleveland',
    state: 'OH',
    fullName: 'Cleveland, OH',
    opportunityScore: 84,
    monthlySearches: 251120,
    competition: 11,
  },
  {
    name: 'Milwaukee',
    slug: 'milwaukee',
    state: 'WI',
    fullName: 'Milwaukee, WI',
    opportunityScore: 84,
    monthlySearches: 253520,
    competition: 16,
  },
  {
    name: 'Memphis',
    slug: 'memphis',
    state: 'TN',
    fullName: 'Memphis, TN',
    opportunityScore: 84,
    monthlySearches: 251120,
    competition: 11,
  },
  {
    name: 'Louisville',
    slug: 'louisville',
    state: 'KY',
    fullName: 'Louisville, KY',
    opportunityScore: 84,
    monthlySearches: 250060,
    competition: 11,
  },
  {
    name: 'Cincinnati',
    slug: 'cincinnati',
    state: 'OH',
    fullName: 'Cincinnati, OH',
    opportunityScore: 84,
    monthlySearches: 249660,
    competition: 17,
  },
  {
    name: 'Des Moines',
    slug: 'des-moines',
    state: 'IA',
    fullName: 'Des Moines, IA',
    opportunityScore: 84,
    monthlySearches: 250670,
    competition: 11,
  },
  {
    name: 'Little Rock',
    slug: 'little-rock',
    state: 'AR',
    fullName: 'Little Rock, AR',
    opportunityScore: 84,
    monthlySearches: 252220,
    competition: 9,
  },
  {
    name: 'Rochester',
    slug: 'rochester',
    state: 'NY',
    fullName: 'Rochester, NY',
    opportunityScore: 84,
    monthlySearches: 248940,
    competition: 9,
  },
  {
    name: 'Tallahassee',
    slug: 'tallahassee',
    state: 'FL',
    fullName: 'Tallahassee, FL',
    opportunityScore: 84,
    monthlySearches: 250040,
    competition: 11,
  },
  {
    name: 'Athens',
    slug: 'athens',
    state: 'GA',
    fullName: 'Athens, GA',
    opportunityScore: 84,
    monthlySearches: 250050,
    competition: 13,
  },
  {
    name: 'Fresno',
    slug: 'fresno',
    state: 'CA',
    fullName: 'Fresno, CA',
    opportunityScore: 84,
    monthlySearches: 251450,
    competition: 11,
  },
  {
    name: 'Chattanooga',
    slug: 'chattanooga',
    state: 'TN',
    fullName: 'Chattanooga, TN',
    opportunityScore: 84,
    monthlySearches: 249710,
    competition: 11,
  },
  {
    name: 'Knoxville',
    slug: 'knoxville',
    state: 'TN',
    fullName: 'Knoxville, TN',
    opportunityScore: 84,
    monthlySearches: 250110,
    competition: 11,
  },
  {
    name: 'Greenville',
    slug: 'greenville',
    state: 'SC',
    fullName: 'Greenville, SC',
    opportunityScore: 84,
    monthlySearches: 249120,
    competition: 4,
  },
  // Batch 3 Expansion - Strong Second Tier (83/100)
  {
    name: 'Omaha',
    slug: 'omaha',
    state: 'NE',
    fullName: 'Omaha, NE',
    opportunityScore: 83,
    monthlySearches: 257360,
    competition: 16,
  },
  {
    name: 'Wichita',
    slug: 'wichita',
    state: 'KS',
    fullName: 'Wichita, KS',
    opportunityScore: 83,
    monthlySearches: 247020,
    competition: 6,
  },
  {
    name: 'Eugene',
    slug: 'eugene',
    state: 'OR',
    fullName: 'Eugene, OR',
    opportunityScore: 83,
    monthlySearches: 248660,
    competition: 16,
  },
  {
    name: 'Gainesville',
    slug: 'gainesville',
    state: 'FL',
    fullName: 'Gainesville, FL',
    opportunityScore: 83,
    monthlySearches: 249930,
    competition: 9,
  },
  {
    name: 'Cambridge',
    slug: 'cambridge',
    state: 'MA',
    fullName: 'Cambridge, MA',
    opportunityScore: 83,
    monthlySearches: 246600,
    competition: 10,
  },
  // Batch 3 Expansion - Solid Third Tier (81/100)
  {
    name: 'Jacksonville',
    slug: 'jacksonville',
    state: 'FL',
    fullName: 'Jacksonville, FL',
    opportunityScore: 81,
    monthlySearches: 250870,
    competition: 20,
  },
  {
    name: 'Spokane',
    slug: 'spokane',
    state: 'WA',
    fullName: 'Spokane, WA',
    opportunityScore: 81,
    monthlySearches: 251440,
    competition: 20,
  },
  {
    name: 'Tacoma',
    slug: 'tacoma',
    state: 'WA',
    fullName: 'Tacoma, WA',
    opportunityScore: 81,
    monthlySearches: 249050,
    competition: 26,
  },
  {
    name: 'Long Beach',
    slug: 'long-beach',
    state: 'CA',
    fullName: 'Long Beach, CA',
    opportunityScore: 81,
    monthlySearches: 249450,
    competition: 23,
  },
  // Batch 3 Expansion - Fourth Tier (74/100)
  {
    name: 'Denver',
    slug: 'denver',
    state: 'CO',
    fullName: 'Denver, CO',
    opportunityScore: 74,
    monthlySearches: 259740,
    competition: 67,
  },
  // Batch 4 Expansion - Top Tier (84/100) - Jan 2026
  {
    name: 'Virginia Beach',
    slug: 'virginia-beach',
    state: 'VA',
    fullName: 'Virginia Beach, VA',
    opportunityScore: 84,
    monthlySearches: 250290,
    competition: 13,
  },
  {
    name: 'Tulsa',
    slug: 'tulsa',
    state: 'OK',
    fullName: 'Tulsa, OK',
    opportunityScore: 84,
    monthlySearches: 253650,
    competition: 11,
  },
  {
    name: 'Reno',
    slug: 'reno',
    state: 'NV',
    fullName: 'Reno, NV',
    opportunityScore: 84,
    monthlySearches: 253640,
    competition: 11,
  },
  {
    name: 'Springfield',
    slug: 'springfield',
    state: 'MO',
    fullName: 'Springfield, MO',
    opportunityScore: 84,
    monthlySearches: 250480,
    competition: 4,
  },
  {
    name: 'Iowa City',
    slug: 'iowa-city',
    state: 'IA',
    fullName: 'Iowa City, IA',
    opportunityScore: 84,
    monthlySearches: 247820,
    competition: 10,
  },
  {
    name: 'Bloomington',
    slug: 'bloomington',
    state: 'IN',
    fullName: 'Bloomington, IN',
    opportunityScore: 84,
    monthlySearches: 247390,
    competition: 4,
  },
  {
    name: 'New Haven',
    slug: 'new-haven',
    state: 'CT',
    fullName: 'New Haven, CT',
    opportunityScore: 84,
    monthlySearches: 246910,
    competition: 4,
  },
  {
    name: 'Baton Rouge',
    slug: 'baton-rouge',
    state: 'LA',
    fullName: 'Baton Rouge, LA',
    opportunityScore: 84,
    monthlySearches: 250800,
    competition: 11,
  },
  {
    name: 'Columbia',
    slug: 'columbia',
    state: 'SC',
    fullName: 'Columbia, SC',
    opportunityScore: 84,
    monthlySearches: 248790,
    competition: 7,
  },
  {
    name: 'Bend',
    slug: 'bend',
    state: 'OR',
    fullName: 'Bend, OR',
    opportunityScore: 84,
    monthlySearches: 246210,
    competition: 3,
  },
  {
    name: 'Ithaca',
    slug: 'ithaca',
    state: 'NY',
    fullName: 'Ithaca, NY',
    opportunityScore: 84,
    monthlySearches: 246390,
    competition: 3,
  },
  // Batch 4 Expansion - Strong Second Tier (83/100)
  {
    name: 'Lexington',
    slug: 'lexington',
    state: 'KY',
    fullName: 'Lexington, KY',
    opportunityScore: 83,
    monthlySearches: 249330,
    competition: 9,
  },
  {
    name: 'Lincoln',
    slug: 'lincoln',
    state: 'NE',
    fullName: 'Lincoln, NE',
    opportunityScore: 83,
    monthlySearches: 247030,
    competition: 9,
  },
  {
    name: 'Anchorage',
    slug: 'anchorage',
    state: 'AK',
    fullName: 'Anchorage, AK',
    opportunityScore: 83,
    monthlySearches: 248800,
    competition: 12,
  },
  {
    name: 'Burlington',
    slug: 'burlington',
    state: 'VT',
    fullName: 'Burlington, VT',
    opportunityScore: 83,
    monthlySearches: 247300,
    competition: 10,
  },
  {
    name: 'Charlottesville',
    slug: 'charlottesville',
    state: 'VA',
    fullName: 'Charlottesville, VA',
    opportunityScore: 83,
    monthlySearches: 247940,
    competition: 9,
  },
  {
    name: 'Birmingham',
    slug: 'birmingham',
    state: 'AL',
    fullName: 'Birmingham, AL',
    opportunityScore: 83,
    monthlySearches: 247100,
    competition: 16,
  },
  // Batch 4 Expansion - Solid Third Tier (82/100)
  {
    name: 'Washington',
    slug: 'washington',
    state: 'DC',
    fullName: 'Washington, DC',
    opportunityScore: 82,
    monthlySearches: 248190,
    competition: 19,
  },
  {
    name: 'Wilmington',
    slug: 'wilmington',
    state: 'NC',
    fullName: 'Wilmington, NC',
    opportunityScore: 82,
    monthlySearches: 249730,
    competition: 15,
  },
  // Batch 4 Expansion - Fourth Tier (80-81/100)
  {
    name: 'Boston',
    slug: 'boston',
    state: 'MA',
    fullName: 'Boston, MA',
    opportunityScore: 81,
    monthlySearches: 259270,
    competition: 30,
  },
  {
    name: 'Fort Worth',
    slug: 'fort-worth',
    state: 'TX',
    fullName: 'Fort Worth, TX',
    opportunityScore: 81,
    monthlySearches: 253570,
    competition: 25,
  },
  {
    name: 'Houston',
    slug: 'houston',
    state: 'TX',
    fullName: 'Houston, TX',
    opportunityScore: 80,
    monthlySearches: 262830,
    competition: 39,
  },
  {
    name: 'Colorado Springs',
    slug: 'colorado-springs',
    state: 'CO',
    fullName: 'Colorado Springs, CO',
    opportunityScore: 80,
    monthlySearches: 255670,
    competition: 28,
  },
  // Batch 4 Expansion - Fifth Tier (77-79/100)
  {
    name: 'Dallas',
    slug: 'dallas',
    state: 'TX',
    fullName: 'Dallas, TX',
    opportunityScore: 79,
    monthlySearches: 259750,
    competition: 38,
  },
  {
    name: 'Portland',
    slug: 'portland-me',
    state: 'ME',
    fullName: 'Portland, ME',
    opportunityScore: 77,
    monthlySearches: 258530,
    competition: 54,
  },
  // Batch 5 Expansion - Final 9 States (Jan 2026)
  // Delaware (DE)
  {
    name: 'Wilmington',
    slug: 'wilmington-de',
    state: 'DE',
    fullName: 'Wilmington, DE',
    opportunityScore: 82,
    monthlySearches: 249730,
    competition: 15,
  },
  // Mississippi (MS)
  {
    name: 'Jackson',
    slug: 'jackson-ms',
    state: 'MS',
    fullName: 'Jackson, MS',
    opportunityScore: 84,
    monthlySearches: 246260,
    competition: 3,
  },
  {
    name: 'Biloxi',
    slug: 'biloxi',
    state: 'MS',
    fullName: 'Biloxi, MS',
    opportunityScore: 84,
    monthlySearches: 246440,
    competition: 4,
  },
  // Montana (MT)
  {
    name: 'Missoula',
    slug: 'missoula',
    state: 'MT',
    fullName: 'Missoula, MT',
    opportunityScore: 83,
    monthlySearches: 248610,
    competition: 10,
  },
  {
    name: 'Bozeman',
    slug: 'bozeman',
    state: 'MT',
    fullName: 'Bozeman, MT',
    opportunityScore: 83,
    monthlySearches: 248100,
    competition: 9,
  },
  {
    name: 'Billings',
    slug: 'billings',
    state: 'MT',
    fullName: 'Billings, MT',
    opportunityScore: 84,
    monthlySearches: 246400,
    competition: 4,
  },
  // New Hampshire (NH)
  {
    name: 'Portsmouth',
    slug: 'portsmouth',
    state: 'NH',
    fullName: 'Portsmouth, NH',
    opportunityScore: 83,
    monthlySearches: 246440,
    competition: 10,
  },
  {
    name: 'Manchester',
    slug: 'manchester',
    state: 'NH',
    fullName: 'Manchester, NH',
    opportunityScore: 82,
    monthlySearches: 246890,
    competition: 14,
  },
  // New Jersey (NJ)
  {
    name: 'Jersey City',
    slug: 'jersey-city',
    state: 'NJ',
    fullName: 'Jersey City, NJ',
    opportunityScore: 83,
    monthlySearches: 247450,
    competition: 12,
  },
  {
    name: 'Hoboken',
    slug: 'hoboken',
    state: 'NJ',
    fullName: 'Hoboken, NJ',
    opportunityScore: 84,
    monthlySearches: 246200,
    competition: 6,
  },
  {
    name: 'Asbury Park',
    slug: 'asbury-park',
    state: 'NJ',
    fullName: 'Asbury Park, NJ',
    opportunityScore: 84,
    monthlySearches: 246520,
    competition: 6,
  },
  {
    name: 'Atlantic City',
    slug: 'atlantic-city',
    state: 'NJ',
    fullName: 'Atlantic City, NJ',
    opportunityScore: 84,
    monthlySearches: 246920,
    competition: 4,
  },
  // North Dakota (ND)
  {
    name: 'Fargo',
    slug: 'fargo',
    state: 'ND',
    fullName: 'Fargo, ND',
    opportunityScore: 84,
    monthlySearches: 249900,
    competition: 7,
  },
  {
    name: 'Bismarck',
    slug: 'bismarck',
    state: 'ND',
    fullName: 'Bismarck, ND',
    opportunityScore: 84,
    monthlySearches: 246390,
    competition: 3,
  },
  // South Dakota (SD)
  {
    name: 'Sioux Falls',
    slug: 'sioux-falls',
    state: 'SD',
    fullName: 'Sioux Falls, SD',
    opportunityScore: 84,
    monthlySearches: 257870,
    competition: 11,
  },
  {
    name: 'Rapid City',
    slug: 'rapid-city',
    state: 'SD',
    fullName: 'Rapid City, SD',
    opportunityScore: 84,
    monthlySearches: 247710,
    competition: 4,
  },
  // West Virginia (WV)
  {
    name: 'Charleston',
    slug: 'charleston-wv',
    state: 'WV',
    fullName: 'Charleston, WV',
    opportunityScore: 84,
    monthlySearches: 249480,
    competition: 10,
  },
  {
    name: 'Morgantown',
    slug: 'morgantown',
    state: 'WV',
    fullName: 'Morgantown, WV',
    opportunityScore: 84,
    monthlySearches: 246140,
    competition: 3,
  },
  // Wyoming (WY)
  {
    name: 'Jackson',
    slug: 'jackson-wy',
    state: 'WY',
    fullName: 'Jackson, WY',
    opportunityScore: 84,
    monthlySearches: 246260,
    competition: 3,
  },
  {
    name: 'Cheyenne',
    slug: 'cheyenne',
    state: 'WY',
    fullName: 'Cheyenne, WY',
    opportunityScore: 83,
    monthlySearches: 247760,
    competition: 7,
  },
  // Google Ads Expansion Cities (Jan 2026) - Low CPC markets
  // Texas
  {
    name: 'Lubbock',
    slug: 'lubbock',
    state: 'TX',
    fullName: 'Lubbock, TX',
    opportunityScore: 85,
    monthlySearches: 6090,
    competition: 8,
  },
  {
    name: 'Amarillo',
    slug: 'amarillo',
    state: 'TX',
    fullName: 'Amarillo, TX',
    opportunityScore: 85,
    monthlySearches: 1900,
    competition: 6,
  },
  // Colorado
  {
    name: 'Fort Collins',
    slug: 'fort-collins',
    state: 'CO',
    fullName: 'Fort Collins, CO',
    opportunityScore: 83,
    monthlySearches: 4420,
    competition: 12,
  },
  // New York
  {
    name: 'Syracuse',
    slug: 'syracuse',
    state: 'NY',
    fullName: 'Syracuse, NY',
    opportunityScore: 86,
    monthlySearches: 1310,
    competition: 4,
  },
  {
    name: 'Albany',
    slug: 'albany',
    state: 'NY',
    fullName: 'Albany, NY',
    opportunityScore: 85,
    monthlySearches: 1000,
    competition: 5,
  },
  // Minnesota
  {
    name: 'Duluth',
    slug: 'duluth',
    state: 'MN',
    fullName: 'Duluth, MN',
    opportunityScore: 85,
    monthlySearches: 1600,
    competition: 6,
  },
  // Alabama
  {
    name: 'Huntsville',
    slug: 'huntsville',
    state: 'AL',
    fullName: 'Huntsville, AL',
    opportunityScore: 84,
    monthlySearches: 1900,
    competition: 8,
  },
  // Kansas
  {
    name: 'Lawrence',
    slug: 'lawrence',
    state: 'KS',
    fullName: 'Lawrence, KS',
    opportunityScore: 87,
    monthlySearches: 590,
    competition: 3,
  },
  // Oklahoma
  {
    name: 'Norman',
    slug: 'norman',
    state: 'OK',
    fullName: 'Norman, OK',
    opportunityScore: 84,
    monthlySearches: 880,
    competition: 8,
  },
] as const

export const STATES = [
  {
    name: 'Texas',
    code: 'TX',
    slug: 'texas',
    cities: ['austin', 'san-antonio', 'el-paso', 'dallas', 'houston', 'fort-worth', 'lubbock', 'amarillo'],
  },
  {
    name: 'California',
    code: 'CA',
    slug: 'california',
    cities: ['los-angeles', 'san-francisco', 'san-diego', 'sacramento', 'fresno', 'long-beach'],
  },
  {
    name: 'Georgia',
    code: 'GA',
    slug: 'georgia',
    cities: ['atlanta', 'savannah', 'athens'],
  },
  {
    name: 'Illinois',
    code: 'IL',
    slug: 'illinois',
    cities: ['chicago'],
  },
  {
    name: 'New York',
    code: 'NY',
    slug: 'new-york',
    cities: ['new-york', 'buffalo', 'rochester', 'ithaca', 'syracuse', 'albany'],
  },
  {
    name: 'Washington',
    code: 'WA',
    slug: 'washington',
    cities: ['seattle', 'spokane', 'tacoma'],
  },
  {
    name: 'Oregon',
    code: 'OR',
    slug: 'oregon',
    cities: ['portland', 'eugene', 'bend'],
  },
  {
    name: 'Florida',
    code: 'FL',
    slug: 'florida',
    cities: ['miami', 'tampa', 'fort-lauderdale', 'jacksonville', 'tallahassee', 'gainesville'],
  },
  {
    name: 'Virginia',
    code: 'VA',
    slug: 'virginia',
    cities: ['richmond', 'virginia-beach', 'charlottesville'],
  },
  {
    name: 'North Carolina',
    code: 'NC',
    slug: 'north-carolina',
    cities: ['asheville', 'charlotte', 'durham', 'raleigh', 'chapel-hill', 'wilmington'],
  },
  {
    name: 'Pennsylvania',
    code: 'PA',
    slug: 'pennsylvania',
    cities: ['philadelphia', 'pittsburgh'],
  },
  {
    name: 'Ohio',
    code: 'OH',
    slug: 'ohio',
    cities: ['columbus', 'cleveland', 'cincinnati'],
  },
  {
    name: 'Utah',
    code: 'UT',
    slug: 'utah',
    cities: ['salt-lake-city'],
  },
  {
    name: 'Tennessee',
    code: 'TN',
    slug: 'tennessee',
    cities: ['nashville', 'memphis', 'chattanooga', 'knoxville'],
  },
  {
    name: 'Arizona',
    code: 'AZ',
    slug: 'arizona',
    cities: ['phoenix', 'tucson'],
  },
  {
    name: 'Nevada',
    code: 'NV',
    slug: 'nevada',
    cities: ['las-vegas', 'reno'],
  },
  {
    name: 'Missouri',
    code: 'MO',
    slug: 'missouri',
    cities: ['kansas-city', 'st-louis', 'springfield'],
  },
  {
    name: 'Louisiana',
    code: 'LA',
    slug: 'louisiana',
    cities: ['new-orleans', 'baton-rouge'],
  },
  {
    name: 'Michigan',
    code: 'MI',
    slug: 'michigan',
    cities: ['detroit', 'ann-arbor'],
  },
  {
    name: 'Rhode Island',
    code: 'RI',
    slug: 'rhode-island',
    cities: ['providence'],
  },
  {
    name: 'South Carolina',
    code: 'SC',
    slug: 'south-carolina',
    cities: ['charleston', 'greenville', 'columbia'],
  },
  {
    name: 'New Mexico',
    code: 'NM',
    slug: 'new-mexico',
    cities: ['albuquerque'],
  },
  {
    name: 'Maryland',
    code: 'MD',
    slug: 'maryland',
    cities: ['baltimore'],
  },
  {
    name: 'Minnesota',
    code: 'MN',
    slug: 'minnesota',
    cities: ['minneapolis', 'duluth'],
  },
  {
    name: 'Wisconsin',
    code: 'WI',
    slug: 'wisconsin',
    cities: ['madison', 'milwaukee'],
  },
  {
    name: 'Oklahoma',
    code: 'OK',
    slug: 'oklahoma',
    cities: ['oklahoma-city', 'tulsa', 'norman'],
  },
  {
    name: 'Hawaii',
    code: 'HI',
    slug: 'hawaii',
    cities: ['honolulu'],
  },
  {
    name: 'Idaho',
    code: 'ID',
    slug: 'idaho',
    cities: ['boise'],
  },
  {
    name: 'Colorado',
    code: 'CO',
    slug: 'colorado',
    cities: ['boulder', 'denver', 'colorado-springs', 'fort-collins'],
  },
  {
    name: 'Indiana',
    code: 'IN',
    slug: 'indiana',
    cities: ['indianapolis', 'bloomington'],
  },
  {
    name: 'Kentucky',
    code: 'KY',
    slug: 'kentucky',
    cities: ['louisville', 'lexington'],
  },
  {
    name: 'Nebraska',
    code: 'NE',
    slug: 'nebraska',
    cities: ['omaha', 'lincoln'],
  },
  {
    name: 'Iowa',
    code: 'IA',
    slug: 'iowa',
    cities: ['des-moines', 'iowa-city'],
  },
  {
    name: 'Kansas',
    code: 'KS',
    slug: 'kansas',
    cities: ['wichita', 'lawrence'],
  },
  {
    name: 'Arkansas',
    code: 'AR',
    slug: 'arkansas',
    cities: ['little-rock'],
  },
  {
    name: 'Massachusetts',
    code: 'MA',
    slug: 'massachusetts',
    cities: ['cambridge', 'boston'],
  },
  {
    name: 'Vermont',
    code: 'VT',
    slug: 'vermont',
    cities: ['burlington'],
  },
  {
    name: 'Connecticut',
    code: 'CT',
    slug: 'connecticut',
    cities: ['new-haven'],
  },
  {
    name: 'Alabama',
    code: 'AL',
    slug: 'alabama',
    cities: ['birmingham', 'huntsville'],
  },
  {
    name: 'Maine',
    code: 'ME',
    slug: 'maine',
    cities: ['portland-me'],
  },
  {
    name: 'Alaska',
    code: 'AK',
    slug: 'alaska',
    cities: ['anchorage'],
  },
  {
    name: 'District of Columbia',
    code: 'DC',
    slug: 'district-of-columbia',
    cities: ['washington'],
  },
  // Batch 5 Expansion - Final 9 States (Jan 2026)
  {
    name: 'Delaware',
    code: 'DE',
    slug: 'delaware',
    cities: ['wilmington-de'],
  },
  {
    name: 'Mississippi',
    code: 'MS',
    slug: 'mississippi',
    cities: ['jackson-ms', 'biloxi'],
  },
  {
    name: 'Montana',
    code: 'MT',
    slug: 'montana',
    cities: ['missoula', 'bozeman', 'billings'],
  },
  {
    name: 'New Hampshire',
    code: 'NH',
    slug: 'new-hampshire',
    cities: ['portsmouth', 'manchester'],
  },
  {
    name: 'New Jersey',
    code: 'NJ',
    slug: 'new-jersey',
    cities: ['jersey-city', 'hoboken', 'asbury-park', 'atlantic-city'],
  },
  {
    name: 'North Dakota',
    code: 'ND',
    slug: 'north-dakota',
    cities: ['fargo', 'bismarck'],
  },
  {
    name: 'South Dakota',
    code: 'SD',
    slug: 'south-dakota',
    cities: ['sioux-falls', 'rapid-city'],
  },
  {
    name: 'West Virginia',
    code: 'WV',
    slug: 'west-virginia',
    cities: ['charleston-wv', 'morgantown'],
  },
  {
    name: 'Wyoming',
    code: 'WY',
    slug: 'wyoming',
    cities: ['jackson-wy', 'cheyenne'],
  },
] as const

export type City = typeof CITIES[number]
export type CitySlug = City['slug']
export type State = typeof STATES[number]
export type StateSlug = State['slug']

// ============================================================================
// International Cities - India
// ============================================================================

export const INDIA_CITIES = [
  { name: 'Mumbai', slug: 'mumbai', state: 'MH', fullName: 'Mumbai, Maharashtra' },
  { name: 'Delhi', slug: 'delhi', state: 'DL', fullName: 'Delhi, Delhi' },
  { name: 'Bangalore', slug: 'bangalore', state: 'KA', fullName: 'Bangalore, Karnataka' },
  { name: 'Kolkata', slug: 'kolkata', state: 'WB', fullName: 'Kolkata, West Bengal' },
  { name: 'Hyderabad', slug: 'hyderabad', state: 'TG', fullName: 'Hyderabad, Telangana' },
  { name: 'Chennai', slug: 'chennai', state: 'TN', fullName: 'Chennai, Tamil Nadu' },
] as const

export const INDIA_STATES = [
  { name: 'Maharashtra', code: 'MH', slug: 'maharashtra', cities: ['mumbai'] },
  { name: 'Delhi', code: 'DL', slug: 'delhi', cities: ['delhi'] },
  { name: 'Karnataka', code: 'KA', slug: 'karnataka', cities: ['bangalore'] },
  { name: 'West Bengal', code: 'WB', slug: 'west-bengal', cities: ['kolkata'] },
  { name: 'Telangana', code: 'TG', slug: 'telangana', cities: ['hyderabad'] },
  { name: 'Tamil Nadu', code: 'TN', slug: 'tamil-nadu', cities: ['chennai'] },
] as const

// ============================================================================
// International Cities - Pakistan
// ============================================================================

export const PAKISTAN_CITIES = [
  { name: 'Karachi', slug: 'karachi', state: 'SD', fullName: 'Karachi, Sindh' },
  { name: 'Lahore', slug: 'lahore', state: 'PB', fullName: 'Lahore, Punjab' },
  { name: 'Islamabad', slug: 'islamabad', state: 'IS', fullName: 'Islamabad, Islamabad Capital' },
  { name: 'Rawalpindi', slug: 'rawalpindi', state: 'PB', fullName: 'Rawalpindi, Punjab' },
] as const

export const PAKISTAN_PROVINCES = [
  { name: 'Sindh', code: 'SD', slug: 'sindh', cities: ['karachi'] },
  { name: 'Punjab', code: 'PB', slug: 'punjab', cities: ['lahore', 'rawalpindi'] },
  { name: 'Islamabad Capital', code: 'IS', slug: 'islamabad-capital', cities: ['islamabad'] },
] as const

export type IndiaCity = typeof INDIA_CITIES[number]
export type IndiaState = typeof INDIA_STATES[number]
export type PakistanCity = typeof PAKISTAN_CITIES[number]
export type PakistanProvince = typeof PAKISTAN_PROVINCES[number]
